# Project: Reus
# Founder: Lotfi Mahiddine
# Organization: Reulink
# Contact: Contact@reulink.app

"""initial schema: agents, memory_records, workflows

Revision ID: c1dd83a102ca
Revises:
Create Date: 2026-07-07 10:27:15.188319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'c1dd83a102ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector explicitly; a fresh database does not enable it by default.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('memory_refs', sa.JSON(), nullable=False),
    sa.Column('operation_log', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('memory_records',
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(384), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index(op.f('ix_memory_records_agent_id'), 'memory_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_memory_records_deleted'), 'memory_records', ['deleted'], unique=False)
    op.create_table('workflows',
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflows')
    op.drop_index(op.f('ix_memory_records_deleted'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_agent_id'), table_name='memory_records')
    op.drop_table('memory_records')
    op.drop_table('agents')
    # Do not drop the vector extension: other objects in this database may use it.
    # ### end Alembic commands ###
